---
- hosts: localhost
  vars_files:
    - config.yaml
  vars_prompt:
    - name: ansible_become_pass
      prompt: Sudo password
      private: true
  tasks:
    - name: Copy configuration files to home directory
      ansible.builtin.copy:
        src: files/
        dest: ~/

    - name: Execute Bash configuration tasks
      ansible.builtin.import_tasks: tasks/bash.yaml

    - name: Configure package sources
      ansible.builtin.import_tasks: tasks/package_sources.yaml
      become: true

    - name: Install required packages
      ansible.builtin.import_tasks: tasks/package.yaml
      become: true

    - name: Install Homebrew package manager
      ansible.builtin.import_tasks: tasks/homebrew.yaml

    - name: Install .NET SDK and runtime
      ansible.builtin.import_tasks: tasks/dotnet.yaml
      when: dotnet | default([]) | length > 0

    - name: Install and configure Docker
      ansible.builtin.import_tasks: tasks/docker.yaml
      become: true
      when: install_docker

    - name: Configure Git
      ansible.builtin.import_tasks: tasks/git.yaml

    - name: Configure OpenSSH
      ansible.builtin.import_tasks: tasks/openssh.yaml

    - name: Configure OpenSSH-Server
      ansible.builtin.import_tasks: tasks/openssh-server.yaml
      become: true
      when: lookup('env', 'NAME') == 'PRECISION-5470'

    - name: Install and configure Pipx
      ansible.builtin.import_tasks: tasks/pipx.yaml

    - name: Configure Ansible
      ansible.builtin.import_tasks: tasks/ansible.yaml
