---
- name: User specific aliases and functions
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    mode: 0640
    marker: >-
      # {mark} USER SPECIFIC ALIASES AND FUNCTIONS
    block: |
      if [ -d ~/.bashrc.d ]; then
          for rc in ~/.bashrc.d/*; do
              if [ -f "$rc" ]; then
                  . "$rc"
              fi
          done
      fi
      unset rc

- ansible.builtin.template:
    src: templates/.bashrc.d/wsl_functions.j2
    dest: ~/.bashrc.d/wsl_functions
    mode: 0640

- ansible.builtin.file:
    path: ~/.local/share/bash-completion/completions
    state: directory
    mode: 0750
