---
- name: Configure user-specific aliases and functions in .bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    mode: 0640
    marker: >-
      # {mark} USER SPECIFIC ALIASES AND FUNCTIONS
    block: |
      if [ -d ~/.bashrc.d ]; then
          for rc in ~/.bashrc.d/*; do
              if [ -f "$rc" ]; then
                  . "$rc"
              fi
          done
      fi
      unset rc

- name: Deploy custom bash functions
  ansible.builtin.template:
    src: templates/.bashrc.d/function.j2
    dest: ~/.bashrc.d/function
    mode: 0640

- name: Ensure bash-completion directory exists
  ansible.builtin.file:
    path: ~/.local/share/bash-completion/completions
    state: directory
    mode: 0750

- name: Ensure ~/.kube directory exists
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0700

- name: Install oh-my-posh
  ansible.builtin.command: curl -s https://ohmyposh.dev/install.sh | bash -s
  args:
    creates: ~/.local/bin/oh-my-posh
