- name: Set DOTNET
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    mode: 0644
    marker: >-
      # {mark} ANSIBLE MANAGED BLOCK DOTNET
    block: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

- name: Download dotnet-install.sh
  ansible.builtin.get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: ~/.local/bin
    mode: u+x

- name: Install dotnet lts
  ansible.builtin.command: dotnet-install.sh --channel lts

- name: Install dotnet preview
  ansible.builtin.command: dotnet-install.sh --channel 9.0 --quality preview

- name: Install powershell
  ansible.builtin.command: dotnet tool update --global powershell

- name: Install Azure Artifacts Credential Provider
  ansible.builtin.shell: >-
    wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash
  args:
    executable: /bin/bash
