- name: Install dotnet dependencies
  ansible.builtin.apt:
    pkg:
      - libc6
      - libgcc-s1
      - libicu76
      - libssl3
      - libstdc++6
      - zlib1g
  become: true

- name: Make sure ~/.local/bin exists
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: 0750

- name: Download dotnet-install.sh
  ansible.builtin.get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: ~/.local/bin
    mode: u+x

- name: Install dotnet
  ansible.builtin.command: >-
    dotnet-install.sh
    --channel {{ item.channel | default('LTS') }}
    --quality {{ item.quality | default('GA') }}
  loop: >-
    {{ dotnet | default([]) }}

- name: dotnet bash completions
  ansible.builtin.copy:
    content: |-
      # bash parameter completion for the dotnet CLI

      function _dotnet_bash_complete()
      {
        local cur="${COMP_WORDS[COMP_CWORD]}" IFS=$'\n' # On Windows you may need to use use IFS=$'\r\n'
        local candidates

        read -d '' -ra candidates < <(dotnet complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)

        read -d '' -ra COMPREPLY < <(compgen -W "${candidates[*]:-}" -- "$cur")
      }

      complete -f -F _dotnet_bash_complete dotnet
    dest: ~/.local/share/bash-completion/completions/dotnet

- name: Install powershell
  ansible.builtin.command: dotnet tool update --global powershell

- name: Install Azure Artifacts Credential Provider
  ansible.builtin.shell: >-
    wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash
  args:
    executable: /bin/bash
