- name: Install dotnet dependencies
  ansible.builtin.apt:
    pkg:
      - libc6
      - libgcc-s1
      - libicu74
      - libssl3
      - libstdc++6
      - zlib1g
  become: yes

- name: Set DOTNET
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    mode: 0640
    marker: >-
      # {mark} ANSIBLE MANAGED BLOCK DOTNET
    block: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

- name: Make sure ~/.local/bin exists
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: 0750

- name: Download dotnet-install.sh
  ansible.builtin.get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: ~/.local/bin
    mode: u+x

- name: Install dotnet
  ansible.builtin.command: >-
    dotnet-install.sh
    --channel {{ item.channel | default('LTS') }}
    --quality {{ item.quality | default('GA') }}
  loop: >-
    {{ dotnet | default([]) }}

- name: Install powershell
  ansible.builtin.command: dotnet tool update --global powershell

- name: Install Azure Artifacts Credential Provider
  ansible.builtin.shell: >-
    wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash
  args:
    executable: /bin/bash
