---
- name: Check if Homebrew directory exists
  ansible.builtin.stat:
    path: /home/linuxbrew
  register: result

- name: Check if Homebrew is installed
  ansible.builtin.assert:
    fail_msg: |
      Homebrew is not installed. Install it using:
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    that: result.stat.exists

- name: Configure Homebrew in ~/.bashrc
  ansible.builtin.copy:
    content: |-
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
      then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
      else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
        do
          [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
        done
      fi
    dest: ~/.bashrc.d/homebrew
    mode: 0640

- name: Update and upgrade Homebrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Add Homebrew taps
  community.general.homebrew_tap:
    name: >-
      {{ item }}
  loop: >-
    {{ homebrew_taps | default([]) }}

- name: Install Homebrew packages
  community.general.homebrew:
    name: >-
      {{ (homebrew_pkg | default([])) + ['oh-my-posh'] }}
    state: present

- name: Check Homebrew completions state
  ansible.builtin.command: brew completions state
  changed_when: false
  register: result

- name: Link Homebrew completions
  ansible.builtin.command: brew completions link
  when: result.stdout != "Completions are linked."
