- ansible.builtin.stat:
    path: /home/linuxbrew
  register: result

- name: Assert that Homebrew is installed
  ansible.builtin.assert:
    fail_msg: |
      Install Homebrew
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    that: result.stat.exists

- name: Homebrew shellenv
  ansible.builtin.copy:
    content: |-
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
      then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
      else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
        do
          [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
        done
      fi
    dest: ~/.bashrc.d/homebrew
    mode: 0640

- name: Homebrew update and upgrade all
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Homebrew install taps
  community.general.homebrew_tap:
    name: >-
      {{ item }}
  loop: >-
    {{ homebrew_taps | default([]) }}

- name: Homebrew install packages
  community.general.homebrew:
    name: >-
      {{ homebrew | default([]) }}
    state: present

- name: Homebrew completions state
  ansible.builtin.command: brew completions state
  changed_when: false
  register: result

- name: Homebrew completions link
  ansible.builtin.command: brew completions link
  when: result.stdout != "Completions are linked."
