---
- name: Create .ssh Directory with Secure Permissions
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Generate ED25519 SSH Key Pair
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    comment: >-
      {{ ansible_facts.env.USER }}@{{ ansible_facts.env.NAME }}
    type: ed25519
    mode: 0600

- name: Generate RSA SSH Key Pair
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    comment: >-
      {{ ansible_facts.env.USER }}@{{ ansible_facts.env.NAME }}
    type: rsa
    mode: 0600

- name: Create SSH Config File from Template
  ansible.builtin.template:
    src: templates/.ssh/config.j2
    dest: ~/.ssh/config
    mode: 0640
