---
- ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: 0750

- name: Generate OpenSSH ED25519 key
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    comment: >-
      {{ ansible_facts.env.USER }}@{{ ansible_facts.env.NAME }}
    type: ed25519

- name: Generate OpenSSH RSA key
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    comment: >-
      {{ ansible_facts.env.USER }}@{{ ansible_facts.env.NAME }}
    type: rsa

- name: export SSH_SK_HELPER
  ansible.builtin.copy:
    content: |-
      export SSH_SK_HELPER="/mnt/c/Program Files/OpenSSH/ssh-sk-helper.exe"
    dest: ~/.bashrc.d/ssh
    mode: 0640

- name: Generate .ssh/config
  ansible.builtin.template:
    src: templates/.ssh/config.j2
    dest: ~/.ssh/config
    mode: 0640
