- name: Install Python packages with pipx
  community.general.pipx:
    name: >-
      {{ item.name }}
    state: latest
    install_deps: >-
      {{ item.deps | default(false) }}
    include_injected: yes
    executable: /usr/bin/pipx
  loop: >-
    {{ pipx | default([]) }}

- name: Inject additional packages into pipx environments
  community.general.pipx:
    name: >-
      {{ item.name }}
    state: inject
    inject_packages: >-
      {{ item.inject | default([]) }}
    executable: /usr/bin/pipx
  loop: >-
    {{ pipx | default([]) }}
