- name: pipx install
  community.general.pipx:
    name: >-
      {{ item.name }}
    state: latest
    install_deps: >-
      {{ item.deps | default(false) }}
    include_injected: yes
    inject_packages: >-
      {{ item.inject | default([]) }}
    executable: /usr/bin/pipx
  loop: >-
    {{ pipx | default([]) }}
