#!/usr/bin/env bash

alias mc="mc --no-x11"

if command -v code-insiders &>/dev/null; then
    alias code=code-insiders
fi

if [ -d $HOME/.ansible ]; then
    alias ansible=$HOME/.ansible/bin/ansible
    alias ansible-builder=$HOME/.ansible/bin/ansible-builder
    alias ansible-community=$HOME/.ansible/bin/ansible-community
    alias ansible-config=$HOME/.ansible/bin/ansible-config
    alias ansible-console=$HOME/.ansible/bin/ansible-console
    alias ansible-doc=$HOME/.ansible/bin/ansible-doc
    alias ansible-galaxy=$HOME/.ansible/bin/ansible-galaxy
    alias ansible-inventory=$HOME/.ansible/bin/ansible-inventory
    alias ansible-playbook=$HOME/.ansible/bin/ansible-playbook
    alias ansible-pull=$HOME/.ansible/bin/ansible-pull
    alias ansible-test=$HOME/.ansible/bin/ansible-test
    alias ansible-vault=$HOME/.ansible/bin/ansible-vault
    # eval "$(register-python-argcomplete $HOME/.ansible/bin/ansible)"
fi
