#!/usr/bin/env bash

alias mc="mc --no-x11"

if command -v code-insiders &>/dev/null; then
    alias code=code-insiders
fi

ansible="~/.ansibile/bin/ansible"
ansible-builder="~/.ansibile/bin/ansible-builder"
ansible-community="~/.ansibile/bin/ansible-community"
ansible-config="~/.ansibile/bin/ansible-config"
ansible-console="~/.ansibile/bin/ansible-console"
ansible-doc="~/.ansibile/bin/ansible-doc"
ansible-galaxy="~/.ansibile/bin/ansible-galaxy"
ansible-inventory="~/.ansibile/bin/ansible-inventory"
ansible-playbook="~/.ansibile/bin/ansible-playbook"
ansible-pull="~/.ansibile/bin/ansible-pull"
ansible-test="~/.ansibile/bin/ansible-test"
ansible-vault="~/.ansibile/bin/ansible-vault"
