#!/usr/bin/env bash
set -euxo pipefail

for target in $HOME/.ansible/bin/ansible*; do
    [ -e $target ] || continue
    basename=$(basename $target)
    linkname="$HOME/.local/bin/$basename"
    if [ -L $linkname ]; then
        if [ "$(readlink $linkname)" != "$target" ]; then
            ln -sf $target $linkname
        fi
    elif [ -e $linkname ]; then
        echo "Warning: $linkname exists and is not a symlink. Skipping."
    else
        ln -s $target $linkname
    fi
done
