#!/usr/bin/env bash

kns() {
    # Check if kubectl is configured with a current context
    if ! kubectl config current-context &>/dev/null; then
        echo "Error: No current-context is set in kubectl. Please configure your Kubernetes context and try again."
        return 1
    fi

    # Fetch namespaces and format them for whiptail menu
    namespaces=$(kubectl get namespaces --template="{{range .items}}{{.metadata.name}} {{end}}")
    IFS=' ' read -r -a namespace_array <<<"$namespaces"

    # Prepare whiptail menu options
    menu_options=()
    for i in "${!namespace_array[@]}"; do
        menu_options+=("$((i + 1))" "${namespace_array[i]}")
    done

    # Get terminal dimensions and reduce by 15%
    full_height=$(tput lines)
    full_width=$(tput cols)
    height=$((full_height - full_height * 15 / 100))
    width=$((full_width - full_width * 15 / 100))

    # Show whiptail menu to select a namespace
    selected_option=$(whiptail --title "Select Namespace" --menu "Choose a namespace:" "$height" "$width" "${#namespace_array[@]}" \
        "${menu_options[@]}" 3>&1 1>&2 2>&3)

    # Export the selected namespace
    if [[ -n "$selected_option" ]]; then
        selected_namespace="${namespace_array[$((selected_option - 1))]}"
        kubectl config set-context --current --namespace=$selected_namespace
    else
        kubectl config set-context --current --namespace=
    fi
}
