# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
---
final_space: true
upgrade:
  auto: true
version: 3
extends: ~/.config/oh-my-posh/themes/cloud-native-azure.omp.json
blocks: []
